name:                note-manager
version:             0.1.1.0
github:              "joedaws/note-manager"
license:             BSD3 
author:              "Joseph D. Daws Jr."
maintainer:          "jozzef@hey.com"
copyright:           "2025 Joseph D. Daws Jr."

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            A tool to create an initialize documents.
# category:            CLI 

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/joedaws/note-manager#readme>

dependencies:
- base >= 4.7 && < 5
- ansi-terminal
- aeson
- bytestring
- process
- time
- yaml
- text

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  noteman:
    main:                Main.hs
    source-dirs:         cli
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - note-manager

tests:
  note-manager-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - note-manager
    - hspec
